// lambda code
void lambda()
{
	auto l = [] {};
	l();
}

// approximately equivalent C++ generated by the compiler
struct Lambda {
	constexpr auto operator()() const {}
};

void equivalent()
{
	auto l = Lambda{};
	l();
}